MamaPesa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView
from django.contrib.sitemaps.views import sitemap
from main.sitemap import ClassSitemap
from django.conf import settings
from django.conf.urls.static import static
sitemaps = {
    'static': ClassSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main.urls')),
    path('vision/', include('vision.urls')),
    path('auth/', include('auth0.urls')),
    path('chat/', include('chatbot.urls')),
    #path('mpesa/', include('mpesa_api.urls')),
    path('google07949db9b98a31b8.html', TemplateView.as_view(template_name="main/google07949db9b98a31b8.html")),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


auth0/urls.py
from django.urls import path, include
from . import views as view_auth
from django.contrib.auth import logout
from django.shortcuts import redirect


def logout_view(request):
    logout(request)
    return redirect('auth0:login')

app_name = "auth0"

urlpatterns =[
    path('register/', view_auth.register, name="register"),
    path('', view_auth.login_view, name="auth"),
    path('login/', view_auth.login_view, name="login"),
    path('logout/', logout_view, name="logout")
]

chatbot/urls.py
from django.urls import path
from . import views


app_name = "chatbot"

urlpatterns = [
    path('', views.index, name="chat"),
    # path("<str:session_id>/", views.room, name="room"),
]

main/urls.py
from django.urls import path, include
from . import views

app_name = "main"

urlpatterns = [
    path("",views.index, name="homepage"),
    path('airtime/', views.airtime, name='airtime'),
    path('about/', views.about, name='about'),
    path('manage/admin/', views.admin_dashboard, name='admin'),
    path('manage/admin/dashboard', views.admin_dashboard, name='admin_dashboard'),
    path('manage/admin/messages', views.admin_get_messages, name='admin_messages'),
]

chatbot/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Chat(models.Model):
    message = models.CharField(max_length=12000)
    image = models.ImageField(upload_to="images/")

class ChatHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="chathistory", null=True)
    history_id = models.CharField(max_length=100, primary_key=True)
    current_history = models.TextField()
    date = models.DateField()

    def __str__(self) -> str:
        return str(self.history_id)

class Messages(models.Model):
    chatHistory = models.ForeignKey(ChatHistory, on_delete=models.CASCADE)
    request_id = models.CharField(max_length=100, null=True)
    message = models.CharField(max_length=30000, null=True)
    image = models.ImageField(upload_to="images/", null=True, blank=True)
    response = models.CharField(max_length=5000)
    date = models.DateTimeField()

    def __str__(self) -> str:
        return str(self.request_id)

main/models.py
from django.db import models
from django.contrib.auth.models import User

class InquiryMessage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="inquiry_message", null=True)
    email = models.EmailField(max_length=100, null=False, blank=False)
    phone = models.CharField(max_length=100,null=True, blank=True)
    user_name = models.CharField(max_length=50)
    message_body = models.TextField()
    message_reference_code = models.CharField(max_length=100)
    message_subject = models.CharField(max_length=100,null=True, blank=True)
    is_urgent = models.BooleanField(null=True, blank=True)
    is_responded = models.BooleanField(null=True, blank=True)
    date = models.DateTimeField()

    def __str__(self) -> str:
        return self.message_reference_code


class InquiryResponse(models.Model):
    message = models.ForeignKey(InquiryMessage, on_delete=models.CASCADE, related_name="inquiry_response", null=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="inquiry_responded", null=True)
    response_reference_code = models.CharField(max_length=100)
    message_response = models.TextField(null=True, blank=True)
    read = models.BooleanField(null=True, blank=True, default=False)
    date = models.DateTimeField()

    def __str__(self) -> str:
        return self.response_reference_code

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse,JsonResponse
import africastalking
from .models import InquiryMessage, InquiryResponse
from datetime import datetime, timedelta
from main . generate_random_hashed_string import Generator
from django.contrib.auth.models import User
from django.core.serializers import serialize
import json
# Create your views here.
def index(request):
    session_id = str(request.session._get_or_create_session_key())
    try:
        user = request.user
        if user.is_authenticated:
            user_groups = user.groups.all()
        
        if request.method == 'POST':
            if request.POST.get("send_message"):
                user_email = request.POST.get("user_email")
                user_name = request.POST.get("user_name")
                urgent = request.POST.get("is_urgent")
                message_body = request.POST.get("message_body")
                form_is_valid = True
                is_urgent = True if urgent else False

                context_response ={
                    'status_code': 'ok', 
                    'message': {'status_ok':'Message sent successfully!'}
                }

                if len(message_body) > 300:
                    context_response['status_code'] = 'error'
                    context_response["message"].pop("status_ok")
                    context_response["message"] = {'status_error_message_body': "Message too long!"}
                    form_is_valid = False
                if len(user_name) > 50:
                    context_response["message"].pop("status_ok")
                    if context_response['status_code'] != 'error':
                        context_response['status_code'] = 'error'
                    context_response["message"]["status_error_user_name"] = "username too long"
                    form_is_valid = False

                if form_is_valid:
                    context_response = send_message_inquiry(request.user,user_email,user_name, is_urgent, message_body, context_response)

                return JsonResponse(context_response)
            if request.POST.get("gmc"):
                if request.user.is_authenticated:
                    context_response = {
                        "is_admin": False,
                        "status_response":{
                            "status_code":"ok",
                            "status_text": "Messages loaded!"
                        },
                        "messages": [],
                        "unread_notifications": 0
                    }
                    context_response = get_user_messages_notifiction(request, context_response)
                else:
                    context_response = {}
                return JsonResponse(context_response)
        return render(request, "main/index.html", {'user':user, 'default': {'session_id': session_id}})
    except Exception as e:
        print(e)
        return HttpResponse(str("Something went wrong!!!..."))
    


def admin_dashboard(request):
    session_id = str(request.session._get_or_create_session_key())
    user = request.user
    if user.is_authenticated:
        if is_user_admin(user):
            if request.method == 'GET':
                inquiries = InquiryMessage.objects.filter(is_responded=False)
                context = {
                    "messages": inquiries
                }
                return render(request, 'main/admin-dashboard.html', {'user':user, 'default':{"session_id": session_id}})
            else:
                if request.POST.get("load_seven_range"):
                    date_range = [datetime.now() - timedelta(days=i) for i in range(7)]
                    user_counts_per_day = {}
                    print(request.GET)
                    for day in date_range:
                        # Calculate the start and end of the day
                        day_start = datetime(day.year, day.month, day.day, 0, 0, 0)
                        day_end = datetime(day.year, day.month, day.day, 23, 59, 59)
                        
                        # Count the number of users who joined on the current day
                        user_count = User.objects.filter(date_joined__range=(day_start, day_end)).count()
                        
                        # Store the count in the dictionary
                        user_counts_per_day[day.strftime('%Y-%m-%d')] = user_count
                    return JsonResponse(user_counts_per_day)
                
                # if request.POST.get("gan"):#gan => get admin notifications
                #     context_response = {
                #         "status_response":{
                #             "status_code": "ok",
                #             "status_text": "Admin notification retrived!"
                #         },
                #         "notification_count": 0,
                #         "notifications": []
                #     }
                #     try:
                #         unread_messages = InquiryMessage.objects.filter(is_responded=False)
                #         message_count = unread_messages.count()
                #         context_response["notification_count"] = message_count
                #         notification_type = {
                #             "type": "messages",
                #             "messages": serialize("json",unread_messages)
                #         }
                #         context_response["notifications"].append(notification_type)
                #     except Exception as e:
                #         print("Error: ", e )
                #         context_response.clear()
                #         context_response["status_response"] = {
                #             "status_code":"error",
                #             "status_text": "Something went wrong! {}".format(str(e))
                #         }
                #     return JsonResponse(context_response)
        
        return HttpResponse(not_authorized())
    else:
        return redirect("auth0:login")


def admin_get_messages(request):
    session_id = str(request.session._get_or_create_session_key())
    user = request.user
    if user.is_authenticated:
        if is_user_admin(user):
            if request.method == 'GET':
                
                return render(request, 'main/admin-messages.html', {'user':user, 'default':{"session_id": session_id}}) 
            else:
                if request.POST.get("get_messages"):
                    inquiries = InquiryMessage.objects.filter(is_responded=False)

                    return JsonResponse(serialize('json', inquiries), safe=False)
                elif request.POST.get("send_reply"):
                    context_response ={
                        'status_code': 'ok', 
                        'message': {'status_ok':'Reply sent successfully!'}
                    }
                    context_response = send_reply(request, context_response)
                    return JsonResponse(context_response)
        else:
            return HttpResponse(not_authorized())
    else:
        return redirect('auth0:login')
def is_user_admin(user):
    is_admin = False
    for group in user.groups.all():
        if group.name == "Admin":
            is_admin = True
            break
    return is_admin

def not_authorized():
    return """
        <html>
        <head>
            <meta http-equiv="refresh" content="2; url='/'">
        </head>
        <body>
            <p>Not authorised to view this page! Redirecting...</p>
        </body>
        </html>
        """
def airtime(res):
    
    username = "softtronic"
    api_key = "c02c7227695535d6988dae4e1379bd0efd491f20d2a4987d6f14f04ccb9fd701"

    africastalking.initialize(username, api_key)

    airtime = africastalking.Airtime

    phone_number = "+254796211581"
    currency_code = "KES" #Change this to your country's code
    amount = 5

    try:
        response = airtime.send(phone_number=phone_number, amount=amount, currency_code=currency_code)
        return HttpResponse(response)
      
    except Exception as e:
        return HttpResponse(f"Encountered an error while sending airtime. More error details below.\n {e}")

def about(request):
    session_id = str(request.session._get_or_create_session_key())
    return render(request, 'main/about.html',{'user':request.user, 'default':{'session_id':session_id}})

def send_message_inquiry(user, user_email, user_name, is_urgent,message_body , context_response):
    date = datetime.now()
    phone = ""
    message_reference_code = Generator(user_email)
    message_subject = "General"
    is_responded = False

    try:
        # Attempt to create and save the InquiryMessage object
        inquiry = InquiryMessage(
            message_reference_code=message_reference_code,
            user=user,
            email=user_email,
            date=date,
            phone=phone,
            message_body=message_body,
            message_subject=message_subject,
            is_urgent=is_urgent,
            is_responded=is_responded,
            user_name=user_name
        )
        inquiry.save()
        user.inquiry_message.add(inquiry)
        context_response['status_code'] = 'ok'
        context_response["message"]["status_ok"] = "Message sent successfully!"
    except Exception as e:
        context_response["message"].pop("status_ok")
        context_response['status_code'] = 'error'
        context_response["message"]["status_error_save"] = "Something went wrong!"
        print("An error occurred:", str(e))
    return context_response

def send_reply(request, context_response):
    message_reference_code = request.POST.get("message_reference_code")
    message_reply = request.POST.get("message_reply")

main/templates/main/admin-messages.html
{% extends 'main/admin.html' %}
{% load static %}
{% block admincontent %}
<script src="{% static 'js\admin-messages.js' %}"></script>

<form method="POST" id="form-get-messages" action="{% url 'main:admin_messages' %}">
    {% csrf_token %}
    <input type="hidden" value="True" name="get_messages">
    <div class="d-flex flex-row no-wrap">
        <div class="h2">Messages</div>
        <button class="mx-md-5 mx-sm-2 border-0 bg-transparent" type="submit"  id="btn-get-messages">
            <i class="fa-solid fa-arrows-rotate"></i><span class="mx-md-2 mx-sm-1">Refresh</span>
        </button>
    </div> 
</form>
<main id="main"></main>

{% endblock %}

main/templates/main/admin.html
{% extends 'main/base.html' %}
{% block title %}
    Admin | Soft Connect
{% endblock %}
{% block class_active_admin %}active{% endblock %}
{% block content %}
<style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


{% block nav-toggle %}
<button class="navbar-toggler d-md-none collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#sidebarMenu" aria-controls="sidebarMenu" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
</button>
{% endblock %}
<div class="container-fluid">
    <style>
        .nav-pills .nav-link{
            font-weight: 500;
            color: #333;
        }
    </style>
<div class="row">
  <nav id="sidebarMenu" class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse">
    <div class="position-fixed bg-light pt-3">
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a class="nav-link link-dark" href="{% url 'main:homepage' %}">
              <span><i class="fa-solid fa-house"></i></span>
              Home
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link link-dark" href="/admin">
              <span><i class="fa-solid fa-user-tie"></i></span>
              Admin
            </a>
          </li>
        <li class="nav-item link-dark">
          <a class="nav-link" aria-current="page" href="{% url 'main:admin_dashboard' %}">
            <span><i class="fa-solid fa-gauge"></i></span>
            Dashboard
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark" href="#">
            <span><i class="fa-solid fa-users"></i></span>
            Staffs
          </a>
        </li>
        <li class="nav-item ">
          <a class="nav-link  bg-primary link-dark position-relative" href="{% url 'main:admin_messages' %}">
            <span><i class="fa-solid fa-message"></i></span>
            Messages
            
            <span class="d-none position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger " id="badge-message-count">
            </span>
            
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark" href="#">
            <span><i class="fa-solid fa-chart-simple"></i></span>
            Trends
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark" href="#">
            <span><i class="fa-solid fa-chart-area"></i></span>
            Reports
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark" href="#">
            <span><i class="fa-solid fa-layer-group"></i></span>
            Integrations
          </a>
        </li>
      </ul>

      <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
        <span>Quick reports</span>
        <a class="link-secondary" href="#" aria-label="Add a new report">
          <span><i class="fa-solid fa-hard-drive"></i></span>
        </a>
      </h6>
      <ul class="nav nav-list flex-column mb-2">
        <li class="nav-item">
          <a class="nav-link link-dark" href="#">
            <span><i class="fa-solid fa-money-check-dollar"></i></span>
            Profits
          </a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-dark" href="#">
            <span><i class="fa-solid fa-scale-balanced"></i></span>
            Year-end sale
          </a>
        </li>
      </ul>
    </div>
  </nav>
  <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
    <style>
      .truncate {
          overflow: hidden;
          white-space: nowrap;
          text-overflow: ellipsis;
      }
      td.truncate {
          max-width: 150px;
      }
    </style>
  {% block admincontent %}
  {% endblock %}
  </main>
</div>
</div>
{% endblock %}

main/templates/main/airtime.html
{% extends 'main/base.html' %}
<div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
    <div class="modal" tabindex="-1">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Modal title</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <p>Modal body text goes here.</p>
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" class="btn btn-primary">Save changes</button>
            </div>
          </div>
        </div>
    </div>
</div>

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="keywords" content="Omukuyia Anthony Alando, Anthony Alando, Omukuyia, Softtronic East Africa, Soft connect, SoftConnect, Gemini API, GPT, AI ChatBot, Chat, AskAI, AI">
    <meta name="og:image" content="https://ik.imagekit.io/anthonyalando/My_Portfolio/anthony-round.png?updatedAt=1679495758645">
    <meta name="image" content="https://ik.imagekit.io/anthonyalando/My_Portfolio/anthony-round.png?updatedAt=1679495758645">
    <meta name="og:title" content="{% block titleOG %}SoftConnect | AI Powered {% endblock %}">
    <meta name="og:description" content="{% block descriptionOg %} Welcome to SoftConnect! Chat with our AI model akin to GPT for instant responses. Explore conversational AI today. {% endblock %}">
    <meta name="title" content="{% block titleWeb %} SoftConnect | AI Powered {% endblock %}">
    <meta name="description" content="{% block descriptionWeb %} Welcome to SoftConnect! Chat with our AI model akin to GPT for instant responses. Explore conversational AI today. {% endblock %}">
    <meta name="author" content="Anthony Alando">
    <link rel="icon" href="https://ik.imagekit.io/anthonyalando/Soft_Connect/SOFTCHAT.png?updatedAt=1713881652505" type="image/png">
    <link rel="canonical" href="{{ request.build_absolute_uri }}">
    {% load static %}
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.9.0/highlight.min.js"></script>

    <script src="https://kit.fontawesome.com/3695de9773.js" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/showdown/2.1.0/showdown.js" integrity="sha512-lK6oZEScytehJvHjR7R03NENoR6dMjpv7PkyQacFi8rux5YxIaYu7tsOCGbZ/RRH8GFnR82LOAp267kxD+q+qQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/feather-icons@4.28.0/dist/feather.min.js" integrity="sha384-uO3SXW5IuS1ZpFPKugNNWqTZRRglnUJK6UAZ/gxOX80nxEkN9NcGZTftn6RzhGWE" crossorigin="anonymous"></script><script src="https://cdn.jsdelivr.net/npm/chart.js@2.9.4/dist/Chart.min.js" integrity="sha384-zNy6FEbO50N+Cg5wap8IKA4M/ZnLJgzc6w2NqACZaK0u0FXfOWRRJOnQtpZun8ha" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/reconnecting-websocket/1.0.0/reconnecting-websocket.min.js" integrity="sha512-B4skI5FiLurS86aioJx9VfozI1wjqrn6aTdJH+YQUmCZum/ZibPBTX55k5d9XM6EsKePDInkLVrN7vPmJxc1qA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="{% static 'js/index.js' %}"></script>

    <title>{% block title %} SoftConnect | AI Powered {% endblock %}</title>
    <style type="text/css">
        @import url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Manrope:wght@200..800&display=swap');
        body *{
            /* font-family: "Roboto", sans-serif; */
            font-family: "Manrope", sans-serif;
            font-optical-sizing: auto;
            /* font-weight: 200; */
            font-style: normal;
        }
        /* code{
            font-size: 16px!important;
        } */
    
    </style>
    
</head>
<body class="p-0 m-0" id="body">
    {% csrf_token %}
    <input id="user_session_id" type="hidden" name="user_session_id" value="{{ default.session_id }}">
    <header class="d-none"><h1>{% block header %} Homepage {% endblock %}</h1></header>
    <nav class="navbar navbar-expand-lg  bg-dark navbar-dark  sticky-top " id="nav">
        
        <div class="container-fluid">
            <a class="navbar-brand" href="/">
                <img src="https://ik.imagekit.io/anthonyalando/Soft_Connect/SOFTCHAT.png?updatedAt=1713881652505" alt="logo" width="30" height="24">
            </a>
            {% block nav-toggle %}
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
            {% endblock %}   
            <div class="collapse navbar-collapse" id="navbarToggle">
                <ul class="nav navbar-nav nav-underline justify-content-center me-auto mb-2 mb-lg-0">

                    <li class="nav-item">
                        <a class="nav-link {% block class_active_home %}{% endblock %}" aria-current="page"  href="/">Home</a>
                    </li>
                    {% for group in user.groups.all %}
                        {% if group.name == "Admin" %}
                        <li class="nav-item">
                            <a class="nav-link {% block class_active_admin %}{% endblock %}" aria-current="page"  href="{% url 'main:admin' %}">Manage</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                    <!-- <li class="nav-item d-none">
                        <a class="nav-link disabled" tabindex="-1" aria-disabled="true" href="/airtime">Utility</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link {% block class_active_vision %}{% endblock %}" href="/vision">Tools</a>
                    </li>
                    <!-- <li class="nav-item d-none">
                        <a class="nav-link disabled" tabindex="-1" aria-disabled="true" href="/mpesa">Mpesa</a>
                    </li> -->
                    <li class="nav-item">
                        <a class="nav-link {% block class_active_about %}{% endblock %}" href="/about">About Us</a>
                    </li>
                    
                    <li class="nav-item">
                        <a type="button" class="btn btn-outline-warning" href="{% url 'chatbot:chat' %}">AI Assistant</a>
                    </li>
                </ul>
                <button type="button" class="btn bg-primary position-relative d-flex m-md-3" id="btn-bell-notification">
                    <i class="fa-regular fa-bell fs-4" id="fa-bell-notification"></i>
                    <span class="position-absolute d-none top-0 start-100 translate-middle badge rounded-pill bg-danger" id="notification-badge">
                        
                        <span class="visually-hidden">unread messages</span>
                      </span>
                  </button>
                <div class="dropdown-center d-flex text-end ms-md-1 me-md-4 my-2 my-md-0">
                    <button class="btn btn-secondary dropdown-toggle p-1" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <img src="https://ik.imagekit.io/anthonyalando/Soft_Connect/user.png?updatedAt=1682239876486" alt="user" width="30" height="30" class="rounded-circle">
                        {% if user.is_authenticated %}
                          {% if user.first_name %}
                              {{user.first_name}}
                          {% elif user.last_name %}
                              {{user.last_name}}
                          {% elif user.username %}
                              {{user.username}}
                          {% else %}
                              Account
                          {% endif %}
                          {% else %}
                              Sign In
                              <span class="position-absolute top-0 start-100 translate-middle badge border border-light rounded-circle bg-warning p-1"><span class="visually-hidden">Login</span></span>
                          {% endif %}
                    </button>
                    <ul class="dropdown-menu">
                      {% if user.is_authenticated %}
                        <li><a class="dropdown-item" href="">Account</a></li>
                        <li><a class="dropdown-item" href="{% url 'auth0:logout' %}">Sign Out</a></li>

                      {% else %}
                      <li><a class="dropdown-item" href="{% url 'auth0:login' %}">Login</a></li>

                        <li><a class="dropdown-item" href="{% url 'auth0:register' %}">Register</a></li>
                      {% endif %}
                    </ul>
                </div>
                <form class="d-flex">
                    <div class="input-group">
                        <input type="search" class="form-control" placeholder="Search" aria-label="Search" aria-describedby="basic-serach">
                        <span class="input-group-text bg-transparent" id="basic-search">
                            <button class="btn btn-outline-none bg-transparent p-0" type="submit">
                                <i class="fa-solid fa-magnifying-glass text-light"></i>
                            </button>
                        </span>
                    </div>
                </form>
                
            </div>
        </div>
    </nav>
    
    <div class="container-fluid overflow-auto position-fixed  p-0 m-0 {% block body-color %} bg-white {% endblock %}" id="body-container">
        {% block content %}
            Homepage
        {% endblock %}
        
    </div>
    <svg xmlns="http://www.w3.org/2000/svg" style="display: none;">
        <symbol id="check-circle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-3.97-3.03a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>
        </symbol>
        <symbol id="info-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm.93-9.412-1 4.705c-.07.34.029.533.304.533.194 0 .487-.07.686-.246l-.088.416c-.287.346-.92.598-1.465.598-.703 0-1.002-.422-.808-1.319l.738-3.468c.064-.293.006-.399-.287-.47l-.451-.081.082-.381 2.29-.287zM8 5.5a1 1 0 1 1 0-2 1 1 0 0 1 0 2z"/>
        </symbol>
        <symbol id="exclamation-triangle-fill" fill="currentColor" viewBox="0 0 16 16">
          <path d="M8.982 1.566a1.13 1.13 0 0 0-1.96 0L.165 13.233c-.457.778.091 1.767.98 1.767h13.713c.889 0 1.438-.99.98-1.767L8.982 1.566zM8 5c.535 0 .954.462.9.995l-.35 3.507a.552.552 0 0 1-1.1 0L7.1 5.995A.905.905 0 0 1 8 5zm.002 6a1 1 0 1 1 0 2 1 1 0 0 1 0-2z"/>
        </symbol>
      </svg>
      {% block modal %}
      {% endblock %}
</body>
</html>

main/templates/main/google07949db9b98a31b8.html
google-site-verification: google07949db9b98a31b8.html